## 필수과제들
- **필수과제1**
-  q1 - pclass 3 이고, age 20세 미만인 남성과, 여성의 카운트 수와 생존수를 비교해 주세요.
    - 코드와 데이터 값

- **필수과제2**
- 요금에 따라 3가지 등급으로 나눠주시고 (요금의 등급의 기준은 기초통계치 분위수 값으로 기준)
    - 해당 분위수에 따라 남성과 여성을 추출하고 카운팅 수, 생존수 비교해 주세요.
    
- **필수과제3**  
- 혼자온 사람과 혼자 오지 않은사람들 중에서 둘을 비교하는데
    - 공통 조건은 혼자 온 사람의 성별 여부에 따른 전체 카운팅과 생존수 비교해 주세요!
    
    
- 필수과제 요구조건
    - 쥬피터노트북, 코드와 주석, 데이터 비교값을 공유

필수과제1

In [2]:
import seaborn as sns

In [6]:
tt=sns.load_dataset('titanic')

In [8]:
tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [10]:
tt_new=tt[(tt['pclass']==3)&(tt['age']<20)]

In [12]:
tt_new

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852,0,3,female,9.0,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
855,1,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,yes,False
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True

In [28]:
tt_new_male=tt_new.query("sex=='male'")

In [30]:
tt_new_male

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
50,0,3,male,7.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
59,0,3,male,11.0,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
63,0,3,male,4.0,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,0,3,male,18.0,0,0,8.3000,S,Third,man,True,NaN,Southampton,no,True
844,0,3,male,17.0,0,0,8.6625,S,Third,man,True,NaN,Southampton,no,True
850,0,3,male,4.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True

In [32]:
tt_new_male.count()

survived       63
pclass         63
sex            63
age            63
sibsp          63
parch          63
fare           63
embarked       63
class          63
who            63
adult_male     63
deck            2
embark_town    63
alive          63
alone          63
dtype: int64

In [34]:
tt_new_female=tt_new.query("sex=='female'")

In [36]:
tt_new_female

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.00,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.00,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
24,0,3,female,8.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
38,0,3,female,18.00,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
39,1,3,female,14.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
44,1,3,female,19.00,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
49,0,3,female,18.00,1,0,17.8000,S,Third,woman,False,NaN,Southampton,no,False
68,1,3,female,17.00,4,2,7.9250,S,Third,woman,False,NaN,Southampton,yes,False
71,0,3,female,16.00,5,2,46.9000,S,Third,woman,False,NaN,Southampton,no,False
111,0,3,female,14.50,1,0,14.4542,C,Third,child,False,NaN,Cherbourg,no,False
114,0,3,female,17.00,0,0,14.4583,C,Third,woman,False,NaN,Cherbourg,no,True
119,0,3,female,2.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
147,0,3,female,9.00,2,2,34.3750,S,Third,child,False,NaN,Southampton,no,False
156,1,3,female,16.00,0,0,7.7333,Q,Third,woman,False,NaN,Queenstown,yes,True
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
192,1,3,female,19.00,1,0,7.8542,S,Third,woman,False,NaN,Southampton,yes,False
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
208,1,3,female,16.00,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
233,1,3,female,5.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
374,0,3,female,3.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
419,0,3,female,10.00,0,2,24.1500,S,Third,child,False,NaN,Southampton,no,False
448,1,3,female,5.00,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
479,1,3,female,2.00,0,1,12.2875,S,Third,child,False,NaN,Southampton,yes,False
541,0,3,female,9.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
542,0,3,female,11.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
634,0,3,female,9.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
642,0,3,female,2.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
654,0,3,female,18.00,0,0,6.7500,Q,Third,woman,False,NaN,Queenstown,no,True
677,1,3,female,18.00,0,0,9.8417,S,Third,woman,False,NaN,Southampton,yes,True
691,1,3,female,4.00,0,1,13.4167,C,Third,child,False,NaN,Cherbourg,yes,False
702,0,3,female,18.00,0,1,14.4542,C,Third,woman,False,NaN,Cherbourg,no,False
777,1,3,female,5.00,0,0,12.4750,S,Third,child,False,NaN,Southampton,yes,True
780,1,3,female,13.00,0,0,7.2292,C,Third,child,False,NaN,Cherbourg,yes,True
786,1,3,female,18.00,0,0,7.4958,S,Third,woman,False,NaN,Southampton,yes,True
807,0,3,female,18.00,0,0,7.7750,S,Third,woman,False,NaN,Southampton,no,True
813,0,3,female,6.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
830,1,3,female,15.00,1,0,14.4542,C,Third,child,False,NaN,Cherbourg,yes,False
852,0,3,female,9.00,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
855,1,3,female,18.00,0,1,9.3500,S,Third,woman,False,NaN,Southampton,yes,False
875,1,3,female,15.00,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True

In [38]:
tt_new_female.count()

survived       45
pclass         45
sex            45
age            45
sibsp          45
parch          45
fare           45
embarked       45
class          45
who            45
adult_male     45
deck            2
embark_town    45
alive          45
alone          45
dtype: int64

-결괏값:

pclass 3 & age<20인 남성:63명
pclass 3 & age<20인 여성:45명